### PR TITLE
Fix issue where the gcp list can contain a None object when no GCP is found in the picture

### LINKED ISSUE #10: If there is no GCP on an image, the program crashes with a TypeError
Hey there,

I started using your program and it's great! However, I found an issue, where if an image has no GCP a None object is pushed in the `self.gcps` list. This leads to a crash when the program tries to iterate over this `None` list.

The full traceback is below.
I already have a fix for this, I will submit a PR.

```
Traceback (most recent call last):
  File "./gcp_find.py", line 452, in <module>
    gcps.gcp_output()
  File "./gcp_find.py", line 230, in gcp_output
    for gcp in gcp_list:
TypeError: 'NoneType' object is not iterable
```

### PR DESCRIPTION
**Pull request by gromain**
Closes #10

### CODE REVIEW

**Comment by zsiki** [comment]
Thanks!
This error was introduced by my latest update :(
I'll probably change the code not to store None values in the gcps list.

**Comment by gromain** [comment]
Yeah, I saw that! I wouldn't have seen the error too.

I'm not sure it will be that easy to fix, since I believe it's an issue with `map` that puts a None in the list when the function returns an empty object. Maybe we can try to not return anything if the list is empty?

**Comment by zsiki** [comment]
I moved one level deeper the filter(None, ...) by commit https://github.com/zsiki/Find-GCP/commit/80723b7050c12031def2c36486636903653cf520, so self.gcps will not store None.
Thanks again for your feedback!

**Comment by gromain** [comment]
Happy to help! I will use this tool quite a lot, so expect more feedback and fixes if needed! ;-)

**Pull request merged**
